phases:
  install:
    commands:
      - docker pull mhart/alpine-node:8
      - docker pull cgswong/aws:aws
  build:
    commands:
      - docker run -e GITHUB_COMMIT=${CODEBUILD_SOURCE_VERSION} -v `pwd`:/usr/local/www.howarddierking.com mhart/alpine-node:8 /usr/local/www.howarddierking.com/build.sh
