version: '2'
services:
  web:
    image: mhart/alpine-node:6
    volumes:
      - .:/usr/local/www.howarddierking.com
    environment:
      - GITHUB_COMMIT=33277432342342432
    ports:
      - "80:8080"
    command: /usr/local/www.howarddierking.com/serve.sh
